import type { CampaignRow, PlatformKey } from "./types";

/**
 * Datos de ejemplo para la vista Medios — mismas filas que se usaron en el
 * Artifact "Pulso Ignite — Perfil Medios" (wireframe), para que el mockup y
 * el mock de la app real coincidan. Se usa mientras no hay WINDSOR_API_KEY,
 * o para una plataforma que todavía no tiene fetcher de campañas (ver
 * app/api/campaigns/route.ts).
 */

const GOOGLE_ADS: CampaignRow[] = [
  {
    accountId: "mock-norte",
    accountName: "Norte Fintech",
    campaignId: "c1",
    campaignName: "Search — Marca",
    impressions: 48200,
    clicks: 2310,
    spend: 54290,
    cpm: 412,
    ctr: 4.8,
    cpl: 890,
    conversions: 61,
    searchImpressionShare: 78,
    qualityScore: 8,
    searchBudgetLostIS: 14,
    searchRankLostIS: 8,
    searchAbsoluteTopIS: 41,
    searchTopIS: 71,
    optimizationScore: 82,
  },
  {
    accountId: "mock-norte",
    accountName: "Norte Fintech",
    campaignId: "c2",
    campaignName: "Search — Genérica",
    impressions: 126400,
    clicks: 3980,
    spend: 91760,
    cpm: 540,
    ctr: 3.1,
    cpl: 1240,
    conversions: 74,
    searchImpressionShare: 44,
    qualityScore: 6,
    searchBudgetLostIS: 39,
    searchRankLostIS: 17,
    searchAbsoluteTopIS: 12,
    searchTopIS: 28,
    optimizationScore: 64,
  },
  {
    accountId: "mock-andes",
    accountName: "Andes Turismo",
    campaignId: "c3",
    campaignName: "Search — Destinos",
    impressions: 89700,
    clicks: 4120,
    spend: 62220,
    cpm: 298,
    ctr: 4.6,
    cpl: 610,
    conversions: 102,
    searchImpressionShare: 61,
    qualityScore: 9,
    searchBudgetLostIS: 22,
    searchRankLostIS: 17,
    searchAbsoluteTopIS: 26,
    searchTopIS: 55,
    optimizationScore: 88,
  },
  {
    accountId: "mock-terra",
    accountName: "Terra Realty",
    campaignId: "c4",
    campaignName: "Display — Remarketing",
    impressions: 210100,
    clicks: 1860,
    spend: 17640,
    cpm: 156,
    ctr: 0.9,
    cpl: 980,
    conversions: 18,
    qualityScore: 7,
    optimizationScore: 55,
    // Sin search_impression_share/lost IS/posición: son campañas de Display, no Search.
  },
  {
    accountId: "mock-metrovoz",
    accountName: "MetroVoz",
    campaignId: "c5",
    campaignName: "Search — Genérica",
    impressions: 64900,
    clicks: 2750,
    spend: 39600,
    cpm: 375,
    ctr: 4.2,
    cpl: 720,
    conversions: 55,
    searchImpressionShare: 52,
    qualityScore: 5,
    searchBudgetLostIS: 31,
    searchRankLostIS: 17,
    searchAbsoluteTopIS: 9,
    searchTopIS: 19,
    optimizationScore: 61,
  },
];

const META_ADS: CampaignRow[] = [
  {
    accountId: "mock-norte",
    accountName: "Norte Fintech",
    campaignId: "m1",
    campaignName: "Reels — Awareness",
    impressions: 184200,
    clicks: 4420,
    spend: 26220,
    cpm: 298,
    ctr: 2.4,
    cpl: 690,
    conversions: 38,
    reach: 96700,
    frequency: 2.1,
  },
  {
    accountId: "mock-andes",
    accountName: "Andes Turismo",
    campaignId: "m2",
    campaignName: "Feed — Conversión",
    impressions: 96400,
    clicks: 1740,
    spend: 29160,
    cpm: 410,
    ctr: 1.8,
    cpl: 540,
    conversions: 54,
    reach: 41200,
    frequency: 3.4,
  },
  {
    accountId: "mock-terra",
    accountName: "Terra Realty",
    campaignId: "m3",
    campaignName: "Stories — Remarketing",
    impressions: 52100,
    clicks: 625,
    spend: 17400,
    cpm: 355,
    ctr: 1.2,
    cpl: 1450,
    conversions: 12,
    reach: 15800,
    frequency: 4.8,
  },
  {
    accountId: "mock-metrovoz",
    accountName: "MetroVoz",
    campaignId: "m4",
    campaignName: "Reels — Lanzamiento",
    impressions: 210900,
    clicks: 6540,
    spend: 29110,
    cpm: 265,
    ctr: 3.1,
    cpl: 410,
    conversions: 71,
    reach: 108600,
    frequency: 1.9,
  },
];

const TIKTOK_ADS: CampaignRow[] = [
  {
    accountId: "mock-norte",
    accountName: "Norte Fintech",
    campaignId: "t1",
    campaignName: "In-Feed — Marca",
    impressions: 312400,
    clicks: 5940,
    spend: 56320,
    cpm: 142,
    ctr: 1.9,
    cpl: 1280,
    conversions: 44,
    reach: 173100,
    frequency: 1.8,
    avgVideoPlaySeconds: 4.1,
    likes: 2140,
  },
  {
    accountId: "mock-andes",
    accountName: "Andes Turismo",
    campaignId: "t2",
    campaignName: "TopView — Lanzamiento",
    impressions: 548900,
    clicks: 14270,
    spend: 87220,
    cpm: 98,
    ctr: 2.6,
    cpl: 980,
    conversions: 89,
    reach: 392100,
    frequency: 1.4,
    avgVideoPlaySeconds: 6.8,
    likes: 5780,
  },
  {
    accountId: "mock-metrovoz",
    accountName: "MetroVoz",
    campaignId: "t3",
    campaignName: "In-Feed — Genérica",
    impressions: 198700,
    clicks: 2190,
    spend: 39690,
    cpm: 165,
    ctr: 1.1,
    cpl: 1890,
    conversions: 21,
    reach: 90300,
    frequency: 2.2,
    avgVideoPlaySeconds: 2.9,
    likes: 890,
  },
];

export const MOCK_CAMPAIGNS: Partial<Record<PlatformKey, CampaignRow[]>> = {
  google: GOOGLE_ADS,
  meta: META_ADS,
  tiktok: TIKTOK_ADS,
};
